app:
  name: Bibliogon
  version: 0.9.0
  description: Open-source book authoring platform
  default_language: de
  delete_permanently: false
  trash_auto_delete_days: 30
  supported_languages:
  - de
  - en
  - es
  - fr
  - el
  - pt
  - tr
  - ja
author:
  name: Asterios Raptis
  pen_names:
  - Draven Quantum
  - Stelio Moon
plugins:
  entry_point_group: bibliogon.plugins
  config_dir: config/plugins
  enabled:
  - export
  - help
  - getstarted
  - ms-tools
  disabled: []
ui:
  title: Bibliogon
  subtitle: Bücher schreiben und exportieren
  logo: assets/logo.svg
  theme: nord
