# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for the Bibliogon launcher (Windows, Linux, macOS).
#
# Build:  poetry run pyinstaller bibliogon-launcher.spec
# Output:
#   Windows: dist/bibliogon-launcher.exe (single-file, windowed, icon embedded)
#   Linux:   dist/bibliogon-launcher (ELF binary)
#   macOS:   dist/Bibliogon Launcher.app (bundle, icon if bibliogon.icns exists)

import os
import sys

block_cipher = None


a = Analysis(
    ["bibliogon_launcher/__main__.py"],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Keep the bundle lean: drop anything we definitely do not import.
        "numpy",
        "pandas",
        "matplotlib",
        "scipy",
        "PIL",  # Pillow is only for the icon-generation script, not runtime.
    ],
    noarchive=False,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="bibliogon-launcher",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # Windows-only: embed icon + version metadata. On non-Windows builds
    # (used only for local smoke by Linux devs), these kwargs are ignored.
    icon=["bibliogon.ico"] if sys.platform == "win32" else None,
    version="version_info.txt" if sys.platform == "win32" else None,
)


# macOS .app bundle. Skipped on Windows and Linux.
# The icon file "bibliogon.icns" is generated by the macOS CI workflow
# (iconutil is macOS-only) before PyInstaller runs. If the file is
# missing, the bundle builds without a custom icon and falls back to
# PyInstaller's default.
if sys.platform == "darwin":
    app = BUNDLE(
        exe,
        name="Bibliogon Launcher.app",
        icon="bibliogon.icns" if os.path.exists("bibliogon.icns") else None,
        bundle_identifier="com.bibliogon.launcher",
        info_plist={
            "CFBundleName": "Bibliogon Launcher",
            "CFBundleDisplayName": "Bibliogon Launcher",
            "CFBundleVersion": "0.1.0",
            "CFBundleShortVersionString": "0.1.0",
            "NSHighResolutionCapable": True,
            "NSRequiresAquaSystemAppearance": False,
        },
    )
