/**
 * The A+ Content ruleset, in the browser (#890).
 *
 * A+ Content is gated desktop-only because both halves of it are Python:
 * the prompt building and the deterministic validator in
 * `bibliogon_aplus`. The validator is the half with no business being
 * server-side - it reads a versioned YAML and returns findings, with no
 * model call and no database - so porting it is what lets the web app
 * check a package the user edited by hand.
 *
 * The ruleset has no API endpoint; it is read straight off disk by the
 * plugin. Its route into the browser is therefore the offline seed,
 * generated by `make generate-seed-data` from
 * `plugins/bibliogon-plugin-aplus/bibliogon_aplus/rules/ruleset.yaml`
 * and committed. What the seed carries is the NORMALIZED ruleset - what
 * `load_ruleset()` returns - so the per-genre fallbacks, the
 * `soft_words.default` unwrapping and the image-style defaults are
 * resolved once in Python instead of being re-implemented here.
 *
 * `make verify-seed-drift` is the gate against a forgotten regeneration;
 * `backend/tests/test_aplus_ruleset_seed.py` pins the shape this module
 * reads.
 *
 * @example
 * const rules = languageRules(getAplusRuleset(), book.language);
 * for (const phrase of rules.marketing_imperatives) { ... }
 */

import seedAplusRuleset from "../../storage/seed/seed-aplus-ruleset.json";

/** The caps Amazon's A+ Content API enforces per field. */
export interface AplusSchemaLimits {
    short_description: number;
    bullet_heading: number;
    bullet_body: number;
    alt_text: number;
}

/** The per-language rules the validator checks text against. */
export interface AplusLanguageRules {
    /** Phrases Amazon reads as marketing imperatives, blocked anywhere. */
    marketing_imperatives: string[];
    /** Price and shipping claims, which A+ Content may not carry at all. */
    price_shipping_terms: string[];
    /** Words that earn a tone warning by default. */
    soft_words_default: string[];
    /** Per-genre-key words that escalate from a warning to an error. */
    genre_escalations: Record<string, string[]>;
    /**
     * Words too common to block mid-sentence, checked only as the FIRST
     * word of a field. English has no imperative inflection, so a bare
     * "build" or "get" is indistinguishable from descriptive prose
     * anywhere else (#828).
     */
    leading_only_imperatives: string[];
}

/** The image-generation style hints, defaulted and per-genre. */
export interface AplusImageStyleRules {
    aspect_ratios: Record<string, string>;
    target_pixel_sizes: Record<string, string>;
    default_model_hint: string;
    default_style_flags: string[];
    genre_model_hints: Record<string, string>;
    genre_style_flags: Record<string, string[]>;
}

/** The whole versioned ruleset, as the seed carries it. */
export interface AplusRuleset {
    /** Bumped whenever a rule changes; a cached package stamps it. */
    version: string;
    schema_limits: AplusSchemaLimits;
    languages: Record<string, AplusLanguageRules>;
    competitor_brands: string[];
    max_regeneration_retries: number;
    image_style: AplusImageStyleRules;
    /** The code `languageRules` falls back to for an unknown language. */
    default_language: string;
    /** The languages the generator accepts, from the loader's constant. */
    supported_languages: string[];
}

const RULESET = seedAplusRuleset as unknown as AplusRuleset;

/** The seeded ruleset. */
export function getAplusRuleset(): AplusRuleset {
    return RULESET;
}

/**
 * The rules for `language`, falling back to the ruleset's default rather
 * than throwing - a typo in a book's language should still get a
 * sensible check instead of crashing the validator. Mirrors
 * `Ruleset.for_language`.
 */
export function languageRules(
    ruleset: AplusRuleset,
    language: string,
): AplusLanguageRules {
    return (
        ruleset.languages[language] ?? ruleset.languages[ruleset.default_language]
    );
}

/**
 * The words that are hard errors for `genreKey` rather than tone
 * warnings. Empty for an unknown or absent genre. Mirrors
 * `LanguageRules.escalated_words`.
 */
export function escalatedWords(
    rules: AplusLanguageRules,
    genreKey: string | null | undefined,
): string[] {
    if (!genreKey) return [];
    return rules.genre_escalations[genreKey] ?? [];
}

/**
 * The `(model_hint, style_flags)` pair for `genreKey`, falling back to
 * the default style when the genre has no override. Mirrors
 * `ImageStyleRules.style_for`.
 */
export function imageStyleFor(
    style: AplusImageStyleRules,
    genreKey: string | null | undefined,
): { modelHint: string; styleFlags: string[] } {
    if (genreKey && genreKey in style.genre_model_hints) {
        return {
            modelHint: style.genre_model_hints[genreKey],
            styleFlags: style.genre_style_flags[genreKey] ?? [],
        };
    }
    return {
        modelHint: style.default_model_hint,
        styleFlags: style.default_style_flags,
    };
}
