/**
 * Smoke for the Medium-Import v2 dry-run preview workflow
 * (MEDIUM-IMPORT-V2-01 Phase 4).
 *
 * The full unit-test coverage lives in:
 *   - backend/tests/test_medium_import_preview.py (preview/import/cancel)
 *   - plugins/.../tests/test_preview.py (cache lifecycle, selection plumbing)
 *   - frontend/src/components/medium-import/MediumImportPreviewTable.test.tsx
 *   - frontend/src/pages/MediumImportPage.test.tsx
 *
 * This spec is the cross-layer regression pin: real browser ->
 * XHR upload -> backend preview parse -> table render -> deselect ->
 * import-selection -> backend import_zip with selected_filenames ->
 * result panel. Catches breaks the per-layer tests can't see (e.g.
 * a wiring bug between the page state-machine and the new API
 * client methods, or a testid-namespace drift on the preview table).
 *
 * Fixture: e2e/fixtures/minimal-medium-export.zip — 2 posts under
 * posts/, generated by regen_minimal_medium_export.py from the
 * plugin's own HTML fixtures.
 */

import {readFileSync} from "node:fs";
import {resolve} from "node:path";

import {test, expect} from "../fixtures/base";

const FIXTURE_PATH = resolve(
    __dirname,
    "..",
    "fixtures",
    "minimal-medium-export.zip",
);
const FIXTURE_BYTES = readFileSync(FIXTURE_PATH);

const POST_A = "01_oldest_tech.html";
const POST_B = "03_english_recent_with_code.html";

test.describe("Medium-Import v2 dry-run preview", () => {
    test("upload -> preview -> deselect one -> import imports only the kept row", async ({
        page,
    }) => {
        await page.goto("/articles/import/medium");
        await expect(page.getByTestId("medium-import-start")).toBeVisible();

        // Upload the minimal Medium ZIP through the hidden file input.
        await page.getByTestId("medium-import-upload-input").setInputFiles({
            name: "minimal-medium-export.zip",
            mimeType: "application/zip",
            buffer: FIXTURE_BYTES,
        });
        await expect(page.getByTestId("medium-import-upload-selected")).toBeVisible();

        // Trigger preview.
        await page.getByTestId("medium-import-start").click();

        // Preview section renders with both rows.
        await expect(page.getByTestId("medium-import-preview-section")).toBeVisible({
            timeout: 15_000,
        });
        await expect(
            page.getByTestId(`medium-import-preview-row-${POST_A}`),
        ).toBeVisible();
        await expect(
            page.getByTestId(`medium-import-preview-row-${POST_B}`),
        ).toBeVisible();

        // Default selection = all checked. The Import button label
        // reflects that (no hard text assertion to stay language-
        // agnostic — the count is what matters).
        const importBtn = page.getByTestId("medium-import-preview-import-btn");
        await expect(importBtn).toBeEnabled();

        // Deselect post B.
        await page
            .getByTestId(`medium-import-preview-row-checkbox-${POST_B}`)
            .click();

        // Run the import.
        await importBtn.click();

        // Result section appears; only 1 article should have been imported
        // (the selected one) and 0 errored.
        await expect(page.getByTestId("medium-import-result")).toBeVisible({
            timeout: 15_000,
        });
        await expect(
            page.getByTestId("medium-import-result-imported-count"),
        ).toContainText("1");
        await expect(
            page.getByTestId("medium-import-result-errored-count"),
        ).toContainText("0");

        // Preview section is gone (success path closes it).
        await expect(
            page.getByTestId("medium-import-preview-section"),
        ).not.toBeVisible();
    });

    test("cancel: clicking Abbrechen returns to idle with file preserved", async ({
        page,
    }) => {
        await page.goto("/articles/import/medium");
        await page.getByTestId("medium-import-upload-input").setInputFiles({
            name: "minimal-medium-export.zip",
            mimeType: "application/zip",
            buffer: FIXTURE_BYTES,
        });
        await page.getByTestId("medium-import-start").click();
        await expect(page.getByTestId("medium-import-preview-section")).toBeVisible({
            timeout: 15_000,
        });

        await page.getByTestId("medium-import-preview-cancel-btn").click();

        await expect(
            page.getByTestId("medium-import-preview-section"),
        ).not.toBeVisible();
        // File stays selected so a second preview-attempt is one click away
        // (mirrors the v0.32.0 "failure preserves user state" contract).
        await expect(page.getByTestId("medium-import-upload-selected")).toBeVisible();
        await expect(page.getByTestId("medium-import-start")).toBeEnabled();
    });

    test("deselect-all: Import button disables when nothing is checked", async ({
        page,
    }) => {
        await page.goto("/articles/import/medium");
        await page.getByTestId("medium-import-upload-input").setInputFiles({
            name: "minimal-medium-export.zip",
            mimeType: "application/zip",
            buffer: FIXTURE_BYTES,
        });
        await page.getByTestId("medium-import-start").click();
        await expect(page.getByTestId("medium-import-preview-section")).toBeVisible({
            timeout: 15_000,
        });

        // Master checkbox click toggles all -> deselect everything in one go.
        await page.getByTestId("medium-import-preview-select-all").click();

        await expect(
            page.getByTestId("medium-import-preview-import-btn"),
        ).toBeDisabled();
    });
});
