/**
 * Smoke for the Medium-Import v2 dry-run preview workflow
 * (MEDIUM-IMPORT-V2-01 + ASYNC-IMPORT-PROGRESS-01).
 *
 * The full unit-test coverage lives in:
 *   - backend/tests/test_medium_import_preview.py (preview/import/cancel)
 *   - backend/tests/test_medium_import_async.py (async endpoint +
 *     SSE event sequence + result endpoint + cancel + cache reap)
 *   - plugins/.../tests/test_preview.py (cache lifecycle, selection
 *     plumbing, progress_callback emission, cooperative cancel)
 *   - frontend/src/components/medium-import/MediumImportPreviewTable.test.tsx
 *   - frontend/src/components/medium-import/MediumImportProgress.test.tsx
 *   - frontend/src/contexts/MediumImportJobContext.test.tsx
 *   - frontend/src/pages/MediumImportPage.test.tsx
 *
 * This spec is the cross-layer regression pin: real browser ->
 * XHR upload -> backend preview parse -> table render -> deselect ->
 * async import submission -> SSE event stream -> per-post progress
 * UI -> result panel. Catches breaks the per-layer tests can't see
 * (a wiring bug between the page state-machine and the new API
 * client methods, a testid-namespace drift on the preview table or
 * progress component, or an SSE event-shape mismatch between the
 * worker and the context).
 *
 * Fixture: e2e/fixtures/minimal-medium-export.zip — 2 posts under
 * posts/, generated by regen_minimal_medium_export.py from the
 * plugin's own HTML fixtures.
 */

import {readFileSync} from "node:fs";
import {resolve} from "node:path";

import {test, expect} from "../fixtures/base";

const FIXTURE_PATH = resolve(
    __dirname,
    "..",
    "fixtures",
    "minimal-medium-export.zip",
);
const FIXTURE_BYTES = readFileSync(FIXTURE_PATH);

const POST_A = "01_oldest_tech.html";
const POST_B = "03_english_recent_with_code.html";

test.describe("Medium-Import v2 dry-run preview", () => {
    test("upload -> preview -> deselect one -> import imports only the kept row", async ({
        page,
    }) => {
        await page.goto("/articles/import/medium");
        await expect(page.getByTestId("medium-import-start")).toBeVisible();

        // Upload the minimal Medium ZIP through the hidden file input.
        await page.getByTestId("medium-import-upload-input").setInputFiles({
            name: "minimal-medium-export.zip",
            mimeType: "application/zip",
            buffer: FIXTURE_BYTES,
        });
        await expect(page.getByTestId("medium-import-upload-selected")).toBeVisible();

        // Trigger preview.
        await page.getByTestId("medium-import-start").click();

        // Preview section renders with both rows.
        await expect(page.getByTestId("medium-import-preview-section")).toBeVisible({
            timeout: 15_000,
        });
        await expect(
            page.getByTestId(`medium-import-preview-row-${POST_A}`),
        ).toBeVisible();
        await expect(
            page.getByTestId(`medium-import-preview-row-${POST_B}`),
        ).toBeVisible();

        // Default selection = all checked. The Import button label
        // reflects that (no hard text assertion to stay language-
        // agnostic — the count is what matters).
        const importBtn = page.getByTestId("medium-import-preview-import-btn");
        await expect(importBtn).toBeEnabled();

        // Deselect post B.
        await page
            .getByTestId(`medium-import-preview-row-checkbox-${POST_B}`)
            .click();

        // Run the import. ASYNC-IMPORT-PROGRESS-01: this submits
        // an async job and the page transitions into the
        // "processing-async" progress UI driven by SSE events.
        await importBtn.click();

        // The SSE-driven progress UI replaces the row-checkbox
        // table's bottom area. For a 2-post import the worker
        // typically completes within a few hundred ms, so the
        // progress UI may flash by quickly; we accept either the
        // progress UI OR the final result panel as the next-state
        // signal to avoid race-based flake.
        const asyncProgress = page.getByTestId("medium-import-progress-async");
        const resultPanel = page.getByTestId("medium-import-result");
        await expect(asyncProgress.or(resultPanel)).toBeVisible({
            timeout: 15_000,
        });

        // Result section appears; only 1 article should have been
        // imported (the selected one) and 0 errored. This is the
        // final SSE-driven transition: stream_end status=completed
        // -> context fetches /jobs/{id}/result -> page renders.
        await expect(resultPanel).toBeVisible({timeout: 30_000});
        await expect(
            page.getByTestId("medium-import-result-imported-count"),
        ).toContainText("1");
        await expect(
            page.getByTestId("medium-import-result-errored-count"),
        ).toContainText("0");

        // Preview section is gone (success path closes it).
        await expect(
            page.getByTestId("medium-import-preview-section"),
        ).not.toBeVisible();
    });

    test("cancel: clicking Abbrechen returns to idle with file preserved", async ({
        page,
    }) => {
        await page.goto("/articles/import/medium");
        await page.getByTestId("medium-import-upload-input").setInputFiles({
            name: "minimal-medium-export.zip",
            mimeType: "application/zip",
            buffer: FIXTURE_BYTES,
        });
        await page.getByTestId("medium-import-start").click();
        await expect(page.getByTestId("medium-import-preview-section")).toBeVisible({
            timeout: 15_000,
        });

        await page.getByTestId("medium-import-preview-cancel-btn").click();

        await expect(
            page.getByTestId("medium-import-preview-section"),
        ).not.toBeVisible();
        // File stays selected so a second preview-attempt is one click away
        // (mirrors the v0.32.0 "failure preserves user state" contract).
        await expect(page.getByTestId("medium-import-upload-selected")).toBeVisible();
        await expect(page.getByTestId("medium-import-start")).toBeEnabled();
    });

    test("async-progress UI: SSE-driven counter ticks then result appears", async ({
        page,
    }) => {
        // Cross-layer pin for the ASYNC-IMPORT-PROGRESS-01 wiring.
        // We deliberately throttle the network so the per-post SSE
        // events are observable rather than racing past the
        // assertion. If a future refactor accidentally drops the
        // SSE subscription (e.g. the context provider isn't
        // mounted, the EventSource URL drifts, the page reads
        // job.* from stale closure) this test will fail loudly.
        await page.goto("/articles/import/medium");
        await page.getByTestId("medium-import-upload-input").setInputFiles({
            name: "minimal-medium-export.zip",
            mimeType: "application/zip",
            buffer: FIXTURE_BYTES,
        });
        await page.getByTestId("medium-import-start").click();
        await expect(page.getByTestId("medium-import-preview-section")).toBeVisible({
            timeout: 15_000,
        });

        await page.getByTestId("medium-import-preview-import-btn").click();

        // Async-progress UI mounts. The counter element renders
        // "X of N posts" — assert the element appears; the
        // numerals themselves race the SSE stream too tightly to
        // assert specific intermediate values without flake.
        await expect(
            page.getByTestId("medium-import-progress-async-counter"),
        ).toBeVisible({timeout: 15_000});

        // Final state: result panel + the preview section is gone.
        await expect(page.getByTestId("medium-import-result")).toBeVisible({
            timeout: 30_000,
        });
        await expect(
            page.getByTestId("medium-import-progress-async"),
        ).not.toBeVisible();
    });

    test("deselect-all: Import button disables when nothing is checked", async ({
        page,
    }) => {
        await page.goto("/articles/import/medium");
        await page.getByTestId("medium-import-upload-input").setInputFiles({
            name: "minimal-medium-export.zip",
            mimeType: "application/zip",
            buffer: FIXTURE_BYTES,
        });
        await page.getByTestId("medium-import-start").click();
        await expect(page.getByTestId("medium-import-preview-section")).toBeVisible({
            timeout: 15_000,
        });

        // Master checkbox click toggles all -> deselect everything in one go.
        await page.getByTestId("medium-import-preview-select-all").click();

        await expect(
            page.getByTestId("medium-import-preview-import-btn"),
        ).toBeDisabled();
    });
});
