/**
 * Offline AI-fill verification (AI 1b). Forces Dexie/offline mode, configures
 * the AI provider against a MOCKED endpoint (page.route), then drives the
 * AITemplatePanel "Fill with AI" flow on an article created + edited entirely
 * offline. Asserts the AI-returned SEO field persists to Dexie (survives a
 * reload) and that ZERO `/api` requests fire throughout.
 *
 * The provider URL (`https://mock-llm.test/...`) is NOT under the app origin's
 * `/api/` path, so the hard `/api` gate below allows it; the mock fulfils it so
 * no real network call leaves the browser. This is the E2E counterpart to the
 * ai/*.test.ts unit coverage.
 *
 * Run by Aster (Pre-Release Gate); the dev server has no service worker, so
 * this exercises the browser-direct LLM path without SW interference.
 */

import {test, expect} from "../fixtures/base";

const MOCK_LLM_BASE = "https://mock-llm.test/v1";
const MOCK_SEO_TITLE = "Mock Offline SEO Title";
const MOCK_SEO_DESCRIPTION = "A search snippet generated by the mocked offline provider.";

test.describe.configure({mode: "serial"});

let apiHits: string[] = [];
let providerCalls = 0;

test.beforeEach(async ({page}) => {
    apiHits = [];
    providerCalls = 0;

    // Force Dexie mode before any app code runs.
    await page.addInitScript(() => {
        try {
            localStorage.setItem("bibliogon.storage_mode", "dexie");
        } catch {
            /* ignore */
        }
    });

    // Hard gate: record + abort every backend /api request (anchored to a
    // `/api/` path right after the origin, so it does NOT match the mocked
    // provider host below).
    await page.route(/^https?:\/\/[^/]+\/api\//, (route) => {
        apiHits.push(route.request().url());
        return route.abort();
    });

    // Mock the LLM provider. The body carries BOTH the OpenAI-compatible shape
    // (`choices[].message.content`) and the Anthropic shape (`content[].text`),
    // so the mock works whichever provider path aiChat takes - no dependency on
    // the seeded provider. The message content is the JSON object the offline
    // aiFill prompts request.
    const aiContent = JSON.stringify({
        seo_title: MOCK_SEO_TITLE,
        seo_description: MOCK_SEO_DESCRIPTION,
    });
    await page.route("https://mock-llm.test/**", (route) => {
        providerCalls += 1;
        return route.fulfill({
            status: 200,
            contentType: "application/json",
            body: JSON.stringify({
                model: "mock-model",
                choices: [{message: {content: aiContent}}],
                content: [{type: "text", text: aiContent}],
                usage: {total_tokens: 42, input_tokens: 30, output_tokens: 12},
            }),
        });
    });
});

test.afterEach(() => {
    expect(
        apiHits,
        `app fired ${apiHits.length} /api call(s) in dexie mode: ${apiHits.join(", ")}`,
    ).toEqual([]);
});

test.describe("Offline AI fill (Dexie mode)", () => {
    test("Fill with AI fills a SEO field via the user's own key, zero /api", async ({
        page,
    }) => {
        // 1. Configure the AI provider in Settings (persists to Dexie via the
        //    settings seam). A mocked base_url + model + a dummy key make
        //    isAiConfigured() true for any provider; the dual-shape mock above
        //    covers whichever request path the seeded provider uses. Wait for
        //    the save toast so the Dexie write lands before navigating away.
        await page.goto("/settings?tab=ai");
        await expect(page.getByTestId("ai-assistant-settings")).toBeVisible({
            timeout: 15_000,
        });
        await page.getByTestId("ai-base-url").fill(MOCK_LLM_BASE);
        // The model field is disabled until a key is present (#451: models
        // load per-provider once a key exists), so fill the key BEFORE the
        // model -- otherwise ai-model stays disabled and .fill() times out.
        await page.getByTestId("ai-api-key-input").fill("sk-mock-offline-key");
        await page.getByTestId("ai-model").fill("mock-model");
        await page.getByTestId("ai-save").click();
        await expect(page.getByText(/Gespeichert|Saved/).first()).toBeVisible({
            timeout: 10_000,
        });

        // 2. Create an article offline; create() persists to Dexie and the page
        //    navigates into the editor.
        await page.goto("/articles/new");
        await page.getByTestId("create-article-title").fill("Offline AI Fill Article");
        await page.getByTestId("create-article-submit").click();
        await expect(page.getByTestId("article-editor")).toBeVisible({
            timeout: 15_000,
        });

        // 3. Give the article body content so extractBodyText is non-empty
        //    (the offline fill rejects an empty article). Autosave debounces to
        //    Dexie, so wait before reading it back through the fill.
        const editor = page.locator(".ProseMirror").first();
        await editor.click();
        await editor.pressSequentially(
            "This article examines coastal climate policy and its effects on city planning.",
        );
        await page.waitForTimeout(1200);

        // 4. Open the AI Template panel's Fill, select the SEO class, submit.
        const fill = page.getByTestId("ai-template-fill");
        await expect(fill).toBeEnabled({timeout: 10_000});
        await fill.click();
        await expect(page.getByTestId("field-class-dialog")).toBeVisible();
        await page.getByTestId("field-class-checkbox-seo").click();
        await page.getByTestId("field-class-submit").click();

        // The dialog closes on success; the provider mock was hit exactly once
        // (one LLM call for the one selected field-class).
        await expect(page.getByTestId("field-class-dialog")).toBeHidden({
            timeout: 15_000,
        });
        expect(providerCalls).toBe(1);

        // 5. Reload: the AI-filled SEO title persisted to Dexie.
        await page.reload();
        await expect(page.getByTestId("article-editor")).toBeVisible({
            timeout: 15_000,
        });
        await expect(page.getByTestId("article-editor-seo-title")).toHaveValue(
            MOCK_SEO_TITLE,
            {timeout: 10_000},
        );
    });

    test("Fill is disabled with a hint when no AI key is configured", async ({
        page,
    }) => {
        // No AI config saved this test -> the readiness probe is not-ready.
        await page.goto("/articles/new");
        await page.getByTestId("create-article-title").fill("No-Key Article");
        await page.getByTestId("create-article-submit").click();
        await expect(page.getByTestId("article-editor")).toBeVisible({
            timeout: 15_000,
        });

        const fill = page.getByTestId("ai-template-fill");
        await expect(fill).toBeDisabled();
        // The configure-key hint, in whichever catalog language the app booted
        // in (German default: "Einstellungen > KI"; English: "Settings > AI").
        await expect(fill).toHaveAttribute(
            "title",
            /Einstellungen > KI|Settings > AI/,
        );
    });
});
