"""Bibliogon installer: download release ZIP and extract to target dir.

Uses stdlib only (``urllib.request``, ``zipfile``, ``tempfile``) so the
PyInstaller bundle stays small. No git dependency.

The install flow:
1. Download release ZIP from GitHub to a temp file
2. Verify ZIP integrity (``zipfile.is_zipfile``)
3. Extract to target directory (strip top-level archive directory)
4. Generate ``.env`` from ``.env.example`` with a random secret
5. Caller writes the install manifest on success

All functions return ``(ok, detail)`` tuples for consistent error
reporting via the launcher's UI layer.
"""

from __future__ import annotations

import logging
import secrets
import shutil
import tempfile
import zipfile
from collections.abc import Callable
from pathlib import Path
from urllib.error import URLError
from urllib.request import urlopen

logger = logging.getLogger("bibliogon_launcher.installer")

GITHUB_REPO = "astrapi69/bibliogon"

# Chunk size for the streamed download. 256 KiB keeps the progress
# callback firing often enough to feel live without thrashing the UI.
_DOWNLOAD_CHUNK = 256 * 1024

# Callback signature: (downloaded_bytes, total_bytes). total_bytes is 0
# when the server sends no Content-Length, in which case the UI shows an
# indeterminate state instead of a percentage.
ProgressCallback = Callable[[int, int], None]


def human_size(num_bytes: int) -> str:
    """Render a byte count as a short human string, e.g. ``"245 MB"``.

    Used for the download progress label. Binary units (1024-based)
    to match what Docker and the OS report. Returns ``"0 B"`` for a
    negative or zero count.
    """
    if num_bytes <= 0:
        return "0 B"
    units = ("B", "KB", "MB", "GB", "TB")
    size = float(num_bytes)
    index = 0
    while size >= 1024 and index < len(units) - 1:
        size /= 1024
        index += 1
    if index == 0:
        return f"{int(size)} {units[index]}"
    return f"{size:.0f} {units[index]}"

# The Bibliogon version this launcher was built for. Updated during
# the release workflow (Step 4) alongside the other version strings.
# Target Bibliogon version this launcher should download for fresh
# installs. Source-of-truth: backend/pyproject.toml.
#
# In a built (PyInstaller) launcher binary, this value is baked in at
# build time via `_build_info.py` (generated by the spec). In dev
# (running tests outside the build) the file does not exist; we fall
# back to a tomllib parse of backend/pyproject.toml. The fallback path
# never ships in a release artifact - it exists only so pytest works
# without invoking PyInstaller first.
try:
    from ._build_info import BIBLIOGON_TARGET_VERSION  # type: ignore
except ImportError:
    import tomllib as _tomllib
    from pathlib import Path as _Path

    _backend_pyproject = (
        _Path(__file__).resolve().parent.parent.parent
        / "backend" / "pyproject.toml"
    )
    try:
        with _backend_pyproject.open("rb") as _f:
            BIBLIOGON_TARGET_VERSION = _tomllib.load(_f)["tool"]["poetry"]["version"]
    except (OSError, KeyError, _tomllib.TOMLDecodeError) as _exc:
        logger.warning(
            "Could not read target version from %s: %s. Using sentinel.",
            _backend_pyproject,
            _exc,
        )
        BIBLIOGON_TARGET_VERSION = "0.0.0+unknown"


def release_zip_url(version: str | None = None) -> str:
    """GitHub archive URL for a tagged release."""
    ver = version or BIBLIOGON_TARGET_VERSION
    tag = ver if ver.startswith("v") else f"v{ver}"
    return f"https://github.com/{GITHUB_REPO}/archive/refs/tags/{tag}.zip"


def download_release(
    target_dir: Path,
    version: str | None = None,
    progress_callback: ProgressCallback | None = None,
) -> tuple[bool, str]:
    """Download and extract a Bibliogon release to ``target_dir``.

    The ZIP from GitHub contains a single top-level directory named
    ``bibliogon-{version}/``. We strip that prefix so files land
    directly inside ``target_dir``.

    ``progress_callback`` is invoked with ``(downloaded_bytes,
    total_bytes)`` as the stream is read so the UI can render a
    progress bar and a "245 MB / 512 MB" label. ``total_bytes`` is 0
    when the server omits ``Content-Length`` (the UI then shows an
    indeterminate state). Callback exceptions never abort the download.

    Returns ``(True, "ok")`` on success, ``(False, detail)`` on failure.
    """
    ver = version or BIBLIOGON_TARGET_VERSION
    url = release_zip_url(ver)
    logger.info("Downloading %s", url)

    tmp_zip = None
    try:
        # Download to temp file (atomic: only use the file if download completes)
        tmp_fd, tmp_zip_path = tempfile.mkstemp(suffix=".zip", prefix="bibliogon-")
        tmp_zip = Path(tmp_zip_path)
        try:
            import os
            os.close(tmp_fd)
            with urlopen(url, timeout=120) as resp, open(tmp_zip, "wb") as out:
                _stream_to_file(resp, out, progress_callback)
        except (URLError, OSError, TimeoutError) as exc:
            return False, f"Download failed: {exc}"

        # Verify ZIP integrity
        if not zipfile.is_zipfile(tmp_zip):
            return False, "Downloaded file is not a valid ZIP archive."

        # Extract with top-level directory stripping
        target_dir.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(tmp_zip, "r") as zf:
            # Find the common prefix (e.g. "bibliogon-0.16.0/")
            names = zf.namelist()
            if not names:
                return False, "ZIP archive is empty."
            prefix = names[0].split("/")[0] + "/"
            for member in zf.infolist():
                if member.is_dir():
                    continue
                # Strip the top-level directory
                rel = member.filename
                if rel.startswith(prefix):
                    rel = rel[len(prefix):]
                if not rel:
                    continue
                dest = target_dir / rel
                dest.parent.mkdir(parents=True, exist_ok=True)
                with zf.open(member) as src, open(dest, "wb") as dst:
                    shutil.copyfileobj(src, dst)

        logger.info("Extracted to %s", target_dir)
        return True, "ok"

    finally:
        # Clean up temp file regardless of outcome
        if tmp_zip and tmp_zip.exists():
            try:
                tmp_zip.unlink()
            except OSError:
                pass


def _total_from_response(resp: object) -> int:
    """Best-effort Content-Length read; 0 when absent or unparseable."""
    try:
        raw = resp.headers.get("Content-Length")  # type: ignore[attr-defined]
    except AttributeError:
        return 0
    try:
        return max(0, int(raw)) if raw is not None else 0
    except (TypeError, ValueError):
        return 0


def _stream_to_file(resp: object, out: object, progress_callback: ProgressCallback | None) -> None:
    """Copy ``resp`` to ``out`` in chunks, reporting progress.

    Mirrors ``shutil.copyfileobj`` but emits ``(downloaded, total)`` to
    ``progress_callback`` after each chunk. A callback that raises is
    swallowed: a broken progress observer must never abort a download.
    """
    total = _total_from_response(resp)
    downloaded = 0
    if progress_callback is not None:
        _safe_progress(progress_callback, 0, total)
    while True:
        chunk = resp.read(_DOWNLOAD_CHUNK)  # type: ignore[attr-defined]
        if not chunk:
            break
        out.write(chunk)  # type: ignore[attr-defined]
        downloaded += len(chunk)
        if progress_callback is not None:
            _safe_progress(progress_callback, downloaded, total)


def _safe_progress(progress_callback: ProgressCallback, downloaded: int, total: int) -> None:
    try:
        progress_callback(downloaded, total)
    except Exception as exc:  # noqa: BLE001 - observer must never break the download
        logger.warning("download progress callback failed: %s", exc)


def create_env_file(repo_dir: Path) -> tuple[bool, str]:
    """Create ``.env`` from ``.env.example`` with a generated secret.

    No-op if ``.env`` already exists (preserves user config on re-install).
    """
    env_file = repo_dir / ".env"
    if env_file.is_file():
        return True, "already exists"

    example = repo_dir / ".env.example"
    if not example.is_file():
        return False, f"{example.name} not found in {repo_dir}"

    try:
        text = example.read_text(encoding="utf-8")
        text = text.replace("change-me-to-a-random-secret", secrets.token_hex(32))
        env_file.write_text(text, encoding="utf-8")
    except OSError as exc:
        return False, f"Failed to create .env: {exc}"

    return True, "created"


def remove_install(install_dir: Path) -> tuple[bool, str]:
    """Remove the Bibliogon installation directory.

    Returns ``(True, "ok")`` on success. On Windows, locked files
    (Docker, running processes) cause ``(False, detail)`` with the
    specific path that could not be removed.
    """
    if not install_dir.exists():
        return True, "already removed"
    try:
        shutil.rmtree(install_dir)
    except OSError as exc:
        return False, f"Could not remove {install_dir}: {exc}"
    return True, "ok"
